insert into User(username, password) values ('darko1234','darko1234');
insert into User(username, password) values ('subscribedUser', 'password');
insert into Channel (channel_name,subscribers,user_id) values ('PewDiePie1',110304078,1);
insert into Channel (channel_name,subscribers,user_id) values ('SerbianGamesBL11',1200034,1);
insert into Channel (channel_name,subscribers,user_id) values ('Darko1',32,1);
insert into Channel (channel_name,subscribers,user_id) values ('CoolChannel1',542,1);
insert into Channel (channel_name,subscribers,user_id) values ('GreatChannel1',203043,1);
insert into Channel (channel_name,subscribers,user_id) values ('AmazingChannel1',43030,1);
insert into Channel (channel_name,subscribers,user_id) values ('SimRacing1',110304,1);
insert into Channel (channel_name,subscribers,user_id) values ('Mudja1',1800034,1);
insert into Channel (channel_name,subscribers,user_id) values ('Darko1231',3232,1);
insert into Channel (channel_name,subscribers,user_id) values ('CoolChannel1231',5424,1);
insert into Channel (channel_name,subscribers,user_id) values ('GreatChannel3211',2030434,1);
insert into Channel (channel_name,subscribers,user_id) values ('AmazingChannel21',430303,1);